/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomeia;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author carlo
 */
public class IngresarMaterial extends javax.swing.JFrame {

    /**
     * Creates new form IngresarMaterial
     */
    public IngresarMaterial() {
        initComponents();
                           
    }
     public Arbol arbol = new Arbol();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPathfoto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresa un nuevo material para reciclaje");

        jLabel2.setText("Nombre Material:");

        jLabel3.setText("Tipo de Material:");

        txtPathfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPathfotoActionPerformed(evt);
            }
        });

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Foto:");

        jLabel5.setText("Tiempo en degradarse: ");

        jLabel6.setText("Meses");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                            .addComponent(txtPathfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addGap(38, 38, 38)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                                .addComponent(txtNombre))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPathfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                JFileChooser dialogo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imgenes", "jpg");
        File ficheroImagen;
        String rutaArchivo;
        dialogo.setFileFilter(filtro);
        int valor = dialogo.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            ficheroImagen = dialogo.getSelectedFile();
            rutaArchivo = ficheroImagen.getPath();               
            txtPathfoto.setText(rutaArchivo);            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPathfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPathfotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPathfotoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        try{
            FileInputStream fis = new FileInputStream(txtPathfoto.getText()); //inFile -> Archivo a copiar
            FileOutputStream fos = new FileOutputStream("C:\\MEIA\\Materiales\\fotografia\\" + txtNombre.getText() + ".jpg"); //outFile -> Copia del archivo
            FileChannel inChannel = fis.getChannel();
            FileChannel outChannel = fos.getChannel();
            inChannel.transferTo(0, inChannel.size(), outChannel);
            fis.close();
            fos.close();
            }catch (IOException ioe) {
            System.err.println("Error al Generar Copia");
            }
        java.util.Date fecha = new Date();
        String fecha_creacion = fecha.toString();
        int estatus = 1;
        int tiempo_degradarse = Integer.parseInt(txtTiempo.getText());
        Material nuevo = new Material(txtNombre.getText(), txtTipo.getText(), txtPathfoto.getText(), ProyectoMEIA.usuarioEnUso.getUsuario(), fecha_creacion, estatus, tiempo_degradarse);

        //MODIFICAR AQUI
        if(OperacionesSecuencialM.obtenerDescriptorMaterial(2).getNumRegistros()!=0){
        int indice = OperacionesSecuencialM.obtenerDescriptorMaterial(2).getNumRegistros() + 1;
            int izquierdo=-1;
            int derecho=-1;
            NodoArbol nuevoNodo = new NodoArbol(indice, izquierdo, derecho, nuevo.Nombre, nuevo.estatus, nuevo.path_imagen, nuevo.tipo, nuevo.tiempo_degradarse, nuevo.usuario_transaccion, nuevo.fecha_creacion);
            nuevoNodo.indice = OperacionesSecuencialM.obtenerDescriptorMaterial(2).getNumRegistros() + 1;
            arbol.agregarNodo(nuevoNodo);                       
            String cadena = arbol.inOrden(arbol.raiz, 0);  
            String textoAnterior = Lector.Obtener("C:/MEIA/Materiales/MaterialBinario.txt");
            if (textoAnterior=="") {
             Escritor.Escribir("C:/MEIA/Materiales/MaterialBinario.txt",textoAnterior+cadena); 
            }else{
             Escritor.Escribir("C:/MEIA/Materiales/MaterialBinario.txt",cadena); 
            }
            DescriptorMaterial des = OperacionesSecuencialM.obtenerDescriptorMaterial(2);           
            des.setNumRegistros(des.getNumRegistros()+1);
            des.setRegistrosActivos(des.getRegistrosActivos()+1);                            
            des.setUsuarioModificacion(nuevo.getNombre());
            Date fechaActual = new Date();
            des.setFechaModificacion(fechaActual.toString());
            OperacionesSecuencialM.rellenarDescriptorMaterial(des, 2);
       }
        else{
            
                    int indice = 1;
                    int izquierdo = -1;
                    int derecho = -1;
                    NodoArbol nuevoNodo = new NodoArbol(indice, izquierdo, derecho, nuevo.Nombre, nuevo.estatus, nuevo.path_imagen, nuevo.tipo, nuevo.tiempo_degradarse, nuevo.usuario_transaccion, nuevo.fecha_creacion);
                    arbol.agregarNodo(nuevoNodo);
                    String cadena = arbol.inOrden(arbol.raiz,0);
                    Escritor.Escribir("C:/MEIA/Materiales/MaterialBinario.txt",cadena);                                     
                    DescriptorMaterial des = OperacionesSecuencialM.obtenerDescriptorMaterial(2);                          
                    des.setNumRegistros(des.getNumRegistros()+1);
                    des.setRegistrosActivos(des.getRegistrosActivos()+1);                            
                    des.setUsuarioCreacion(nuevo.getNombre());
                    des.setUsuarioModificacion(nuevo.getNombre());
                    Date fechaActual = new Date();
                    des.setFechaCreacion(fechaActual.toString());
                    des.setFechaModificacion(fechaActual.toString());
                    OperacionesSecuencialM.rellenarDescriptorMaterial(des, 2);      
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
                Materiales registro = new Materiales();
                        registro.setVisible(true);
                        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarMaterial().setVisible(true);
            }
        });
    }
    
        boolean VerSiExisteMaterial(Material us){
        try{
            LinkedList<Material> Materiales = OperacionesSecuencialM.obtenerMateriales(1);
            for (int i = 0; i < Materiales.size(); i++) {
                if(us.getNombre().equals(Materiales.get(i).getNombre())){
                    return true;
                }
            }
         if(OperacionesSecuencialM.obtenerDescriptorMaterial(1).getNumRegistros()!=0){
              Materiales = OperacionesSecuencialM.obtenerMateriales(2);
            for (int i = 0; i < Materiales.size(); i++) {
                if(us.getNombre().equals(Materiales.get(i).getNombre())){
                    return true;
                }
            }
         }   
           
            
            return false;
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error al leer el archivo");
            return true;
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPathfoto;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
