/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomeia;

import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.ParseException;
import java.util.Date;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author garya
 */
public class OpcionesAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesAdministrador
     */
    public OpcionesAdministrador() {
        initComponents();
        lUsuario.setText(ProyectoMEIA.usuarioEnUso.getUsuario());
        ImageIcon image = new ImageIcon(ProyectoMEIA.usuarioEnUso.getPathFoto());  
        int scale = 3;   
        int width = image.getIconWidth();  
        int height = image.getIconHeight();  
        BufferedImage buffer = new BufferedImage(width*scale, height*scale, BufferedImage.TYPE_INT_ARGB);  
        Graphics2D graphics = buffer.createGraphics();  
        graphics.scale(scale,scale);  
        image.paintIcon(null, graphics, 0, 0);  
        graphics.dispose();  
        jLabel2.setIcon(new ImageIcon(buffer));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBackUp = new javax.swing.JButton();
        BtnIngresarUsuarios = new javax.swing.JButton();
        btnModificarDatos = new javax.swing.JButton();
        btnBuscarUsuarios = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lUsuario = new javax.swing.JLabel();
        lRol = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMateriales = new javax.swing.JButton();
        btnDonacion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Reportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnBackUp.setText("Realizar copia de seguridad");
        btnBackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUpActionPerformed(evt);
            }
        });

        BtnIngresarUsuarios.setText("Ingresar Usuarios");
        BtnIngresarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarUsuariosActionPerformed(evt);
            }
        });

        btnModificarDatos.setText("Modificar Datos");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });

        btnBuscarUsuarios.setText("Buscar Usuarios");
        btnBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuariosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FOTO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Menú de Administrador");

        jLabel5.setText("Usuario:");

        jLabel6.setText("Rol:");

        jLabel3.setText("Administrador");

        btnMateriales.setText("Listado de materiales");
        btnMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialesActionPerformed(evt);
            }
        });

        btnDonacion.setText("Agregar Donacion");
        btnDonacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonacionActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar Donacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Reportes.setText("Reportes de Donaciones");
        Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBackUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnIngresarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(btnDonacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(Reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsuario)
                    .addComponent(lRol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lUsuario)
                                .addGap(22, 22, 22)
                                .addComponent(lRol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87)
                        .addComponent(btnSalir)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnIngresarUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMateriales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDonacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(Reportes)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void copiarDirectorio(String origen, String destino) {
    comprobarCrearDirectorio(destino);
    File directorio = new File(origen);
    File f;
    if (directorio.isDirectory()) {
        comprobarCrearDirectorio(destino);
        String [] files = directorio.list();
        if (files.length > 0) {
            for (String archivo : files) {
                f = new File (origen + File.separator + archivo);
                if(f.isDirectory()) {
                    comprobarCrearDirectorio(destino+File.separator+archivo+File.separator);
                    copiarDirectorio(origen+File.separator+archivo+File.separator, destino+File.separator+archivo+File.separator);
                } else { //Es un archivo
                    copiarArchivo(origen+File.separator+archivo, destino+File.separator+archivo);
                }
            }
        }
    }
}
private void copiarArchivo(String sOrigen, String sDestino) {
    try {
        File origen = new File(sOrigen);
        File destino = new File(sDestino);
        InputStream in = new FileInputStream(origen);
        OutputStream out = new FileOutputStream(destino);

        byte[] buf = new byte[1024];
        int len;

        while ((len = in.read(buf)) > 0) {
            out.write(buf, 0, len);
        }

        in.close();
        out.close();

    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
}
private void comprobarCrearDirectorio(String ruta) {
    File directorio = new File(ruta);
    if (!directorio.exists()) {
        directorio.mkdirs();
    }
}
    private void btnBackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUpActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser Chooser= new javax.swing.JFileChooser();
        Chooser.setSelectedFile(new File("MEIA_Backup"));        
        File fFile=Chooser.getSelectedFile();
        Chooser.setCurrentDirectory(new File("MEIA_Backup"));
        Chooser.setSelectedFile (fFile);
        String ruta = ""; 
       try{ 
        if(Chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){ 
        ruta = Chooser.getSelectedFile().getAbsolutePath(); 
        copiarDirectorio("C:\\MEIA",ruta);       
       String contenidoUsuario= Lector.Obtener("C:\\MEIA\\usuario.txt");
       contenidoUsuario+=Lector.Obtener("C:\\MEIA\\Bitacora_Usuario.txt");
      
        Escritor.Escribir(ruta,contenidoUsuario);
        Date fecha=new Date();
        File bitacora=new File("C:\\MEIA\\desc_bitacora_backup.txt");
        DescriptorBitacoraBackup descriptor=new DescriptorBitacoraBackup();
        if(!bitacora.exists()){
            Date fechaActual=new Date();
            descriptor.setFechaCreacion(fechaActual.toString());
            descriptor.setUsuarioCreacion(ProyectoMEIA.usuarioEnUso.getUsuario());
            descriptor.setNombre("bitacora_backup");
            descriptor.setNumRegistros(1);
            Escritor.Escribir("C:\\MEIA\\desc_bitacora_backup.txt", descriptor.toString());
        }
        else{
            DescriptorBitacoraBackup desc=OperacionesSecuencial.obtenerDescriptorBB();
            Date fechaAct=new Date();
            desc.setFechaModificacion(fechaAct.toString());
            desc.setUsuarioModificacion(ProyectoMEIA.usuarioEnUso.getUsuario());
            desc.setNumRegistros(desc.getNumRegistros()+1);
            Escritor.Escribir("C:\\MEIA\\desc_bitacora_backup.txt", desc.toString());
        }
        AgregarBitacora(new BitacoraBackup(ruta,ProyectoMEIA.usuarioEnUso.getUsuario(),fecha.toString()));
} 
}catch (HeadlessException ex){ 
} 
    }//GEN-LAST:event_btnBackUpActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         LogIn ventana=null;
            try {
                ventana = new LogIn();
            } catch (IOException ex) {
                Logger.getLogger(OpcionesUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            ventana.show();
            dispose(); 
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void BtnIngresarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarUsuariosActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            RegistroUsuario registro = new RegistroUsuario(false);
            registro.setVisible(true);
            this.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnIngresarUsuariosActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        // TODO add your handling code here:
          OpcionesUsuario registro = new OpcionesUsuario();
                        registro.setVisible(true);
                        this.setVisible(false);
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuariosActionPerformed
        // TODO add your handling code here:
          BuscarUsuarios registro = new BuscarUsuarios();
                        registro.setVisible(true);
                        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarUsuariosActionPerformed

    private void btnMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialesActionPerformed
        // TODO add your handling code here:
        Materiales registro = new Materiales();
                        registro.setVisible(true);
                        this.setVisible(false);
    }//GEN-LAST:event_btnMaterialesActionPerformed

    private void btnDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonacionActionPerformed
        // TODO add your handling code here:
        IngresarDonacion registro = new IngresarDonacion();
                        registro.setVisible(true);
                        this.setVisible(false);
    }//GEN-LAST:event_btnDonacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EncontrarDonacion registro = new EncontrarDonacion();
                        registro.setVisible(true);
                        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesActionPerformed
        // TODO add your handling code here:
        CrearReportes reportes = new CrearReportes();
        reportes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesAdministrador().setVisible(true);
            }
        });
    }
        public void AgregarBitacora(BitacoraBackup datosBitacora){
        File ArchivoBitacora=new File("C:\\MEIA\\bitacora_backup.txt");
        if(!ArchivoBitacora.exists()){
            Escritor.Escribir("C:\\MEIA\\bitacora_backup.txt", datosBitacora.toString());
            
        }else{
            String contenidoExistente=Lector.Obtener("C:\\MEIA\\bitacora_backup.txt");
            contenidoExistente+=datosBitacora.toString();
            Escritor.Escribir("C:\\MEIA\\bitacora_backup.txt", contenidoExistente);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresarUsuarios;
    private javax.swing.JButton Reportes;
    private javax.swing.JButton btnBackUp;
    private javax.swing.JButton btnBuscarUsuarios;
    private javax.swing.JButton btnDonacion;
    private javax.swing.JButton btnMateriales;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lRol;
    private javax.swing.JLabel lUsuario;
    // End of variables declaration//GEN-END:variables
}
