/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomeia;
import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luisc
 */
public class ReporteDonacionFecha extends javax.swing.JFrame {

    /**
     * Creates new form ReporteDonacionFecha
     */
    public ReporteDonacionFecha() {
        initComponents();
        LlenarCombobox();
    }
    
    public void LlenarCombobox()
    {        
        ArrayList<String> n1= new ArrayList<String>();
        try { //Se busca al usuario ingresado en el archivo de texto
                String path ="";                
                int bloque =1;
                path = "C:\\MEIA\\Donaciones\\Donacion_"+bloque+".txt";
                File n2 = new File(path);                
                while(n2.exists())
                {
                FileReader Donaciones = new FileReader(path);
                BufferedReader DonacionesBuffer = new BufferedReader(Donaciones);
                String line;                
                line = DonacionesBuffer.readLine();
                while ( line != null) 
                {   
                    String[] partes = line.split("\\|");                                         
                    if (partes[8]!="0") {
                        if (n1.contains(partes[2])) {
                            //No se agrega
                        }
                        else
                        {
                            n1.add(partes[2]);
                        }
                    }
                    line = DonacionesBuffer.readLine();                    
                }
                Donaciones.close();
                DonacionesBuffer.close();
                bloque++;
                path = "C:\\MEIA\\Donaciones\\Donacion_"+bloque+".txt";
                n2 = new File(path);
                }              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        DefaultComboBoxModel CB = new DefaultComboBoxModel(n1.toArray());
        Fechas.setModel(CB);
    }
    public void LlenarGrid(ArrayList<DonacionReporte> Rows)
    {        
        Collections.sort(Rows);
        DefaultTableModel model= (DefaultTableModel) this.LlenarPorFecha.getModel();        
        model.setRowCount(0);
        Object rowData[] = new Object[5];
        for (int i = 0; i < Rows.size(); i++) {
            rowData[0] = Rows.get(i).Material;
            rowData[1] = Rows.get(i).Donador;
            rowData[2] = Rows.get(i).FechaDonacion;
            rowData[3] = Rows.get(i).Peso;
            rowData[4] = Rows.get(i).Descripcion;
            model.addRow(rowData);
        }
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fechas = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LlenarPorFecha = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fechas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechasActionPerformed(evt);
            }
        });

        LlenarPorFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material", "Donador", "Fecha Donacion", "Peso", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(LlenarPorFecha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Fechas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(37, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechasActionPerformed
        // TODO add your handling code here:
        String selected = this.Fechas.getSelectedItem().toString();
        ArrayList<DonacionReporte> Rows = new ArrayList<DonacionReporte>();
        try { //Se busca al usuario ingresado en el archivo de texto
                String path ="";                
                int bloque =1;
                path = "C:\\MEIA\\Donaciones\\Donacion_"+bloque+".txt";
                File n1 = new File(path);                
                while(n1.exists())
                {
                    FileReader Donaciones = new FileReader(path);
                BufferedReader DonacionesBuffer = new BufferedReader(Donaciones);
                String line;                
                line = DonacionesBuffer.readLine();
                while ( line != null) 
                {   
                    String[] partes = line.split("\\|");
                    DonacionReporte aux = new DonacionReporte();                    
                    aux.Material= partes[1];
                    aux.Donador = partes[6];
                    aux.Peso = Integer.parseInt(partes[3]);
                    aux.Descripcion = partes[4];
                    aux.FechaDonacion=partes[2];                           
                    if (partes[8]!="0"&&partes[2].equals(selected)) {
                        Rows.add(aux);
                    }
                    line = DonacionesBuffer.readLine();                    
                }
                Donaciones.close();
                DonacionesBuffer.close();
                bloque++;
                path = "C:\\MEIA\\Donaciones\\Donacion_"+bloque+".txt";
                n1 = new File(path);
                }              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        this.LlenarGrid(Rows);
    }//GEN-LAST:event_FechasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteDonacionFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteDonacionFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteDonacionFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteDonacionFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteDonacionFecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Fechas;
    private javax.swing.JTable LlenarPorFecha;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
