/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomeia;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luisc
 */
public class ReporteDonaciones extends javax.swing.JFrame {

    /**
     * Creates new form ReporteDonaciones
     */
    ArrayList<DonacionReporte> Rows = new ArrayList<DonacionReporte>();
    public ReporteDonaciones() {
        initComponents();
        LlenarLista();
    }
    public void LlenarLista()
    {
        try { //Se busca al usuario ingresado en el archivo de texto
                String path ="";                
                int bloque =1;
                path = "C:\\MEIA\\Donaciones\\Donacion_"+bloque+".txt";
                File n1 = new File(path);                
                while(n1.exists())
                {
                    FileReader Donaciones = new FileReader(path);
                BufferedReader DonacionesBuffer = new BufferedReader(Donaciones);
                String line;                
                line = DonacionesBuffer.readLine();
                while ( line != null) 
                {   
                    String[] partes = line.split("\\|");
                    DonacionReporte aux = new DonacionReporte();                    
                    aux.Material= partes[1];
                    aux.Donador = partes[6];
                    aux.Peso = Integer.parseInt(partes[3]);
                    aux.Descripcion = partes[4];
                    aux.FechaDonacion=partes[2];                           
                    if (partes[8]!="0") {
                        Rows.add(aux);
                    }
                    line = DonacionesBuffer.readLine();                    
                }
                Donaciones.close();
                DonacionesBuffer.close();
                bloque++;
                path = "C:\\MEIA\\Donaciones\\Donacion_"+bloque+".txt";
                n1 = new File(path);
                }              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        LlenarGrid();
        
    }
    
    public void LlenarGrid()
    {
        Collections.sort(Rows);
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[5];
        for (int i = 0; i < Rows.size(); i++) {
            rowData[0] = Rows.get(i).Material;
            rowData[1] = Rows.get(i).Donador;
            rowData[2] = Rows.get(i).FechaDonacion;
            rowData[3] = Rows.get(i).Peso;
            rowData[4] = Rows.get(i).Descripcion;
            model.addRow(rowData);
        }
        
        
        
    }
            
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material", "Donador", "Fecha Donacion", "Peso", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteDonaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteDonaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteDonaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteDonaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteDonaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
