/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomeia;
import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luisc
 */
public class ReporteDonacionFecha extends javax.swing.JFrame {

    /**
     * Creates new form ReporteDonacionFecha
     */
    public ReporteDonacionFecha() {
        initComponents();
        
    }   
    
    public void LlenarRows()
    {
        ArrayList<DonacionReporte> Rows = new ArrayList<DonacionReporte>();
        try { //Se busca al usuario ingresado en el archivo de texto
                String path ="";                
                int bloque =1;
                path = "C:\\MEIA\\Donaciones\\Donacion_"+bloque+".txt";
                File n1 = new File(path);                
                while(n1.exists())
                {
                    FileReader Donaciones = new FileReader(path);
                BufferedReader DonacionesBuffer = new BufferedReader(Donaciones);
                String line;                
                line = DonacionesBuffer.readLine();
                while ( line != null) 
                {   
                    String[] partes = line.split("\\|");
                    DonacionReporte aux = new DonacionReporte();                    
                    aux.Material= partes[1];
                    aux.Donador = partes[6];
                    aux.Peso = Integer.parseInt(partes[3]);
                    aux.Descripcion = partes[4];
                    aux.FechaDonacion=partes[2];                           
                    if (partes[8]!="0") {
                        DateFormat form1 = new SimpleDateFormat("dd/MMMM/yyyy", Locale.ENGLISH);
                        Date date1 = form1.parse(aux.FechaDonacion);
                        
                        if (date1.compareTo(FechaInicio.getDate())>0 && date1.compareTo(FechaFin.getDate())<0) {
                            Rows.add(aux);
                            
                        }
                        
                    }
                    line = DonacionesBuffer.readLine();                    
                }
                Donaciones.close();
                DonacionesBuffer.close();
                bloque++;
                path = "C:\\MEIA\\Donaciones\\Donacion_"+bloque+".txt";
                n1 = new File(path);
                }              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        LlenarGrid(Rows);
    }
    
    
    public void LlenarGrid(ArrayList<DonacionReporte> Rows)
    {        
        Collections.sort(Rows);
        DefaultTableModel model= (DefaultTableModel) this.LlenarPorFecha.getModel();        
        model.setRowCount(0);
        Object rowData[] = new Object[5];
        for (int i = 0; i < Rows.size(); i++) {
            rowData[0] = Rows.get(i).Material;
            rowData[1] = Rows.get(i).Donador;
            rowData[2] = Rows.get(i).FechaDonacion;
            rowData[3] = Rows.get(i).Peso;
            rowData[4] = Rows.get(i).Descripcion;
            model.addRow(rowData);
        }
        
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        LlenarPorFecha = new javax.swing.JTable();
        Salir = new javax.swing.JButton();
        FechaInicio = new com.toedter.calendar.JDateChooser();
        FechaFin = new com.toedter.calendar.JDateChooser();
        LlenarGrid = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        LlenarPorFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material", "Donador", "Fecha Donacion", "Peso", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(LlenarPorFecha);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        LlenarGrid.setText("LlenarGrid");
        LlenarGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlenarGridActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha de Inicio");

        jLabel2.setText("Fecha Fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(LlenarGrid)
                .addGap(60, 60, 60)
                .addComponent(Salir)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Salir)
                        .addComponent(LlenarGrid)))
                .addContainerGap(306, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(37, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        CrearReportes ventana=null;
        ventana = new CrearReportes();
            ventana.show();
            dispose(); 
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void LlenarGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlenarGridActionPerformed
        // TODO add your handling code here:
        LlenarRows();
    }//GEN-LAST:event_LlenarGridActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteDonacionFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteDonacionFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteDonacionFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteDonacionFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteDonacionFecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaFin;
    private com.toedter.calendar.JDateChooser FechaInicio;
    private javax.swing.JButton LlenarGrid;
    private javax.swing.JTable LlenarPorFecha;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
